### ISSUE TITLE
Error on list monitors if account has error-tracking monitor

### ISSUE THREAD

**Issue by pmargreff** [DataDog/datadog-api-client-ruby#793]
**Describe the bug**
If an account has monitors for error tracking the API client will fail to list monitors. 

**To Reproduce**

1. Create a Datadog monitor for error tracking.
2. For the same account try to [fetch all monitors](https://docs.datadoghq.com/api/latest/monitors/#get-all-monitor-details) using the ruby client. That should raise an exception, blocking the user to get monitors. 

**Expected behavior**
I can fetch all monitors for an account even when the user has error tracking monitors configured. 

**Exception**
```ruby 
RuntimeError

Invalid ENUM value error-tracking alert for class #MonitorType
```

```ruby
/home/opslevel/vendor/ruby/2.6.0/gems/datadog_api_client-1.2.0/lib/datadog_api_client/v1/models/monitor_type.rb:46:in `build_from_hash'
/home/opslevel/vendor/ruby/2.6.0/gems/datadog_api_client-1.2.0/lib/datadog_api_client/v1/models/monitor_type.rb:38:in `build_from_hash'
/home/opslevel/vendor/ruby/2.6.0/gems/datadog_api_client-1.2.0/lib/datadog_api_client/v1/models/monitor.rb:358:in `_deserialize'
/home/opslevel/vendor/ruby/2.6.0/gems/datadog_api_client-1.2.0/lib/datadog_api_client/v1/models/monitor.rb:309:in `block in build_from_hash'
/home/opslevel/vendor/ruby/2.6.0/gems/datadog_api_client-1.2.0/lib/datadog_api_client/v1/models/monitor.rb:299:in `each_pair'
/home/opslevel/vendor/ruby/2.6.0/gems/datadog_api_client-1.2.0/lib/datadog_api_client/v1/models/monitor.rb:299:in `build_from_hash'
/home/opslevel/vendor/ruby/2.6.0/gems/datadog_api_client-1.2.0/lib/datadog_api_client/v1/models/monitor.rb:291:in `build_from_hash'
/home/opslevel/vendor/ruby/2.6.0/gems/datadog_api_client-1.2.0/lib/datadog_api_client/v1/api_client.rb:283:in `convert_to_type'
/home/opslevel/vendor/ruby/2.6.0/gems/datadog_api_client-1.2.0/lib/datadog_api_client/v1/api_client.rb:273:in `block in convert_to_type'
/home/opslevel/vendor/ruby/2.6.0/gems/datadog_api_client-1.2.0/lib/datadog_api_client/v1/api_client.rb:273:in `map'
/home/opslevel/vendor/ruby/2.6.0/gems/datadog_api_client-1.2.0/lib/datadog_api_client/v1/api_client.rb:273:in `convert_to_type'
/home/opslevel/vendor/ruby/2.6.0/gems/datadog_api_client-1.2.0/lib/datadog_api_client/v1/api_client.rb:243:in `deserialize'
/home/opslevel/vendor/ruby/2.6.0/gems/datadog_api_client-1.2.0/lib/datadog_api_client/v1/api_client.rb:76:in `call_api'
/home/opslevel/vendor/ruby/2.6.0/gems/datadog_api_client-1.2.0/lib/datadog_api_client/v1/api/monitors_api.rb:414:in `list_monitors_with_http_info'
/home/opslevel/vendor/ruby/2.6.0/gems/datadog_api_client-1.2.0/lib/datadog_api_client/v1/api/monitors_api.rb:339:in `list_monitors'
```

**Environment and Versions (please complete the following information):**
A clear and precise description of your setup:
ruby: `2.6.0`
datadog_api_client: `datadog_api_client (1.2.0)`

**Additional context**

**Comment by therve** [comment]
Thanks for the report. The error tracking team is on it and should push an update soon.

**Comment by therve** [comment]
Fixed in #808 , thanks.

**Comment by pmargreff** [comment]
Awesome, thank you. Do you happen to know when the next release will happen @therve ?

**Comment by jirikuncar** [comment]
It should be publish soon https://github.com/DataDog/datadog-api-client-ruby/pull/810.
